<script lang="ts">
  let step = 1
  const totalSteps = 5

  let config = {
    os: '',
    apiProvider: '',
    apiKey: '',
    model: '',
    port: '3001'
  }

  const MODELS: Record<string, Array<{value: string; label: string}>> = {
    anthropic: [
      { value: 'claude-3-5-sonnet-20241022', label: 'Claude Sonnet 4 (recommended)' },
      { value: 'claude-3-haiku-20240307', label: 'Claude Haiku (fast, cheap)' },
      { value: 'claude-opus-4-5', label: 'Claude Opus (most powerful)' }
    ],
    openrouter: [
      { value: 'anthropic/claude-sonnet-4-6', label: 'Claude Sonnet 4 via OpenRouter (recommended)' },
      { value: 'openai/gpt-4o', label: 'GPT-4o via OpenRouter' },
      { value: 'google/gemini-pro', label: 'Gemini Pro via OpenRouter' }
    ],
    openai: [
      { value: 'gpt-4o', label: 'GPT-4o (recommended)' },
      { value: 'gpt-4o-mini', label: 'GPT-4o mini (fast, cheap)' }
    ]
  }

  $: availableModels = MODELS[config.apiProvider] || []

  function generateConfig() {
    return `# OpenClaw Gateway Configuration
# Generated by ClawMaster Config Wizard

provider: ${config.apiProvider}
model: ${config.model}
port: ${config.port}

# Your API key (keep this secret!)
# Set via environment variable:
# export OPENCLAW_API_KEY="${config.apiKey}"
`
  }

  function generateCommands() {
    const installCmd = {
      mac: 'brew install node && npm install -g openclaw',
      windows: 'winget install OpenJS.NodeJS && npm install -g openclaw',
      linux: 'curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash - && sudo apt install -y nodejs && npm install -g openclaw'
    }[config.os] || 'npm install -g openclaw'

    return `# Step 1: Install Node.js and OpenClaw
${installCmd}

# Step 2: Set your API key
export OPENCLAW_API_KEY="${config.apiKey || 'YOUR_API_KEY_HERE'}"

# Step 3: Initialize OpenClaw
openclaw init --provider ${config.apiProvider || 'anthropic'} --model ${config.model || 'claude-3-5-sonnet-20241022'}

# Step 4: Start the Gateway
openclaw gateway start

# Step 5: Open the Control UI
open http://localhost:${config.port}`
  }

  let copied = ''
  function copy(text: string, key: string) {
    navigator.clipboard.writeText(text)
    copied = key
    setTimeout(() => { copied = '' }, 2000)
  }
</script>

<svelte:head>
  <title>Gateway Setup Wizard — ClawMaster</title>
</svelte:head>

<div class="min-h-screen bg-[#0d1117]">
  <nav class="border-b border-slate-800 px-6 py-4 flex items-center gap-4">
    <a href="/config" class="text-slate-400 hover:text-white text-sm transition">← Config Wizards</a>
    <span class="text-slate-700">|</span>
    <span class="text-white font-semibold">⚡ Gateway Setup</span>
  </nav>

  <div class="max-w-2xl mx-auto px-4 py-12">
    <!-- Progress -->
    <div class="mb-8">
      <div class="flex justify-between text-xs text-slate-500 mb-2">
        <span>Step {step} of {totalSteps}</span>
        <span>{Math.round((step / totalSteps) * 100)}%</span>
      </div>
      <div class="h-2 bg-slate-800 rounded-full">
        <div class="h-full bg-gradient-to-r from-orange-500 to-red-500 rounded-full transition-all" style="width: {(step / totalSteps) * 100}%"></div>
      </div>
    </div>

    {#if step === 1}
      <div class="bg-[#161b22] border border-slate-700 rounded-2xl p-8">
        <h2 class="text-white text-xl font-bold mb-2">What operating system are you using?</h2>
        <p class="text-slate-400 text-sm mb-6">We'll give you the right installation commands.</p>
        <div class="space-y-3">
          {#each [['mac', '🍎 macOS'], ['windows', '🪟 Windows'], ['linux', '🐧 Linux / Raspberry Pi']] as [value, label]}
            <button
              class="w-full text-left px-5 py-4 rounded-xl border transition font-medium {config.os === value ? 'border-orange-500 bg-orange-500/10 text-white' : 'border-slate-700 hover:border-slate-500 text-slate-300'}"
              on:click={() => config.os = value}
            >{label}</button>
          {/each}
        </div>
      </div>

    {:else if step === 2}
      <div class="bg-[#161b22] border border-slate-700 rounded-2xl p-8">
        <h2 class="text-white text-xl font-bold mb-2">Which AI provider will you use?</h2>
        <p class="text-slate-400 text-sm mb-6">OpenRouter gives you access to 100+ models with one API key (recommended for beginners).</p>
        <div class="space-y-3">
          {#each [['openrouter', '🔀 OpenRouter (recommended)', '100+ models with one key'], ['anthropic', '🎭 Anthropic', 'Claude models directly'], ['openai', '🤖 OpenAI', 'GPT models directly']] as [value, label, desc]}
            <button
              class="w-full text-left px-5 py-4 rounded-xl border transition {config.apiProvider === value ? 'border-orange-500 bg-orange-500/10' : 'border-slate-700 hover:border-slate-500'}"
              on:click={() => { config.apiProvider = value; config.model = MODELS[value]?.[0]?.value || '' }}
            >
              <p class="text-white font-medium">{label}</p>
              <p class="text-slate-400 text-xs">{desc}</p>
            </button>
          {/each}
        </div>
      </div>

    {:else if step === 3}
      <div class="bg-[#161b22] border border-slate-700 rounded-2xl p-8">
        <h2 class="text-white text-xl font-bold mb-2">Enter your API key</h2>
        <p class="text-slate-400 text-sm mb-2">
          {#if config.apiProvider === 'openrouter'}
            Get your key at <a href="https://openrouter.ai" target="_blank" class="text-orange-400 hover:underline">openrouter.ai</a> → API Keys
          {:else if config.apiProvider === 'anthropic'}
            Get your key at <a href="https://console.anthropic.com" target="_blank" class="text-orange-400 hover:underline">console.anthropic.com</a> → API Keys
          {:else}
            Get your key at <a href="https://platform.openai.com/api-keys" target="_blank" class="text-orange-400 hover:underline">platform.openai.com</a> → API Keys
          {/if}
        </p>
        <div class="bg-amber-500/10 border border-amber-500/30 rounded-xl p-3 mb-6 text-amber-300 text-sm">
          ⚠️ This key stays in your browser and is used only to generate config commands. It's never stored on our servers.
        </div>
        <input
          type="password"
          bind:value={config.apiKey}
          placeholder="sk-or-v1-... or sk-ant-..."
          class="w-full px-4 py-3 bg-[#0d1117] border border-slate-600 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-orange-500"
        />
      </div>

    {:else if step === 4}
      <div class="bg-[#161b22] border border-slate-700 rounded-2xl p-8">
        <h2 class="text-white text-xl font-bold mb-2">Select your AI model</h2>
        <p class="text-slate-400 text-sm mb-6">For most users, the recommended model is the best choice.</p>
        <div class="space-y-3">
          {#each availableModels as model}
            <button
              class="w-full text-left px-5 py-4 rounded-xl border transition font-medium {config.model === model.value ? 'border-orange-500 bg-orange-500/10 text-white' : 'border-slate-700 hover:border-slate-500 text-slate-300'}"
              on:click={() => config.model = model.value}
            >{model.label}</button>
          {/each}
        </div>
      </div>

    {:else if step === 5}
      <div class="bg-[#161b22] border border-slate-700 rounded-2xl p-8">
        <h2 class="text-white text-xl font-bold mb-2">🎉 Your Config is Ready!</h2>
        <p class="text-slate-400 text-sm mb-6">Copy and run these commands in your terminal.</p>

        <!-- Setup Commands -->
        <div class="mb-6">
          <div class="flex items-center justify-between bg-slate-800 px-3 py-2 rounded-t-lg">
            <span class="text-slate-400 text-xs">Terminal</span>
            <button
              on:click={() => copy(generateCommands(), 'cmd')}
              class="text-xs text-slate-400 hover:text-white px-2 py-0.5 bg-slate-700 hover:bg-slate-600 rounded transition"
            >
              {copied === 'cmd' ? '✓ Copied!' : 'Copy'}
            </button>
          </div>
          <pre class="bg-[#0a0e14] border border-slate-700 border-t-0 rounded-b-lg p-4 overflow-x-auto text-sm text-slate-200 font-mono whitespace-pre-wrap">{generateCommands()}</pre>
        </div>

        <div class="p-4 bg-green-500/10 border border-green-500/30 rounded-xl text-sm text-green-400">
          ✅ After running these commands, your Gateway will be running at <code class="bg-green-500/20 px-1 rounded">http://localhost:{config.port}</code>
        </div>

        <div class="mt-6 flex gap-4">
          <a href="/chat" class="flex-1 text-center py-3 bg-orange-600 hover:bg-orange-700 text-white font-semibold rounded-xl transition">
            Ask ClawBot for help →
          </a>
          <a href="/learn" class="flex-1 text-center py-3 border border-slate-700 hover:border-slate-500 text-slate-300 rounded-xl transition">
            Browse modules
          </a>
        </div>
      </div>
    {/if}

    <!-- Navigation -->
    {#if step < totalSteps}
      <div class="flex gap-4 mt-6">
        {#if step > 1}
          <button on:click={() => step--} class="flex-1 py-3 border border-slate-700 hover:border-slate-500 text-slate-300 font-semibold rounded-xl transition">← Back</button>
        {/if}
        <button
          on:click={() => step++}
          disabled={
            (step === 1 && !config.os) ||
            (step === 2 && !config.apiProvider) ||
            (step === 4 && !config.model)
          }
          class="flex-1 py-3 bg-orange-600 hover:bg-orange-700 disabled:bg-slate-700 disabled:text-slate-500 text-white font-semibold rounded-xl transition"
        >
          Next →
        </button>
      </div>
    {/if}
  </div>
</div>
